-- return {
-- 	{
-- 		"nvim-neo-tree/neo-tree.nvim",
-- 		branch = "v3.x",
-- 		dependencies = {
-- 			"nvim-lua/plenary.nvim",
-- 			"nvim-tree/nvim-web-devicons",
-- 			"MunifTanjim/nui.nvim",
-- 		},
-- 		config = function()
-- 			local neotree = require("neo-tree")
-- 			neotree.setup({
-- 				default_component_configs = {
-- 					indent = {
-- 						indent_size = 4,
-- 						padding = 1, -- extra padding on left hand side
-- 						-- indent guides
-- 						with_markers = true,
-- 						indent_marker = "│",
-- 						last_indent_marker = "└",
-- 						highlight = "NeoTreeIndentMarker",
-- 						-- expander config, needed for nesting files
-- 						with_expanders = nil, -- if nil and file nesting is enabled, will enable expanders
-- 						expander_collapsed = "",
-- 						expander_expanded = "",
-- 						expander_highlight = "NeoTreeExpander",
-- 					},
-- 					icon = {
-- 						folder_closed = "",
-- 						folder_open = "",
-- 						folder_empty = "󰜌",
-- 						default = "*",
-- 						highlight = "NeoTreeFileIcon",
-- 					},
-- 				},
-- 				filesystem = {
-- 					filtered_items = {
-- 						visible = true,
-- 						hide_dotfiles = false,
-- 						hide_gitignored = false,
-- 						hide_by_name = {
-- 							-- '.git',
-- 							-- '.DS_Store',
-- 							-- 'thumbs.db',
-- 						},
-- 						never_show = {},
-- 					},
-- 				},
-- 			})
-- 		end,
-- 	},
-- }
--
return {}
